# Generated by Django 2.2.24 on 2024-12-02 10:16
from django.db import migrations


def fill_owners_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all().iterator():
        owner_flats = Flat.objects.filter(owner=owner.owner)
        owner.flats.set(owner_flats)
        owner.save()


def move_backwards(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().update(flats=[])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20241202_1316'),
    ]

    operations = [
        migrations.RunPython(fill_owners_flats, move_backwards)
    ]
