# Generated by Django 2.2.24 on 2024-12-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20241202_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='fullname',
        ),
    ]
